name: Deploy to Hugging Face Space

on:
  push:
    branches: [ hf-deploy ]   # or main; push to this branch to deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source (with LFS metadata)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
          persist-credentials: false

      - name: Create deploy snapshot
        run: |
          # Make a clean staging folder
          rm -rf deploy && mkdir deploy
          rsync -av --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.gitmodules' \
            --exclude 'submodules/TTS/tests/' \
            --exclude 'submodules/whisper/tests/' \
            --exclude 'submodules/whisperX/figures/' \
            --exclude 'submodules/demucs/test.mp3' \
            deploy/

          # If your app truly doesn't need docs/examples at runtime, drop them:
          rm -rf deploy/docs || true
          rm -rf deploy/examples || true

      - name: Init new repo for Space push
        working-directory: deploy
        run: |
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Track common binary types using Git LFS (pointers only in commit)
          git lfs install
          cat > .gitattributes <<'EOF'
*.png filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
*.jpeg filter=lfs diff=lfs merge=lfs -text
*.gif filter=lfs diff=lfs merge=lfs -text
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.wav filter=lfs diff=lfs merge=lfs -text
*.flac filter=lfs diff=lfs merge=lfs -text
*.npy filter=lfs diff=lfs merge=lfs -text
*.pt  filter=lfs diff=lfs merge=lfs -text
*.pth filter=lfs diff=lfs merge=lfs -text
*.ttf filter=lfs diff=lfs merge=lfs -text
EOF
          git add .gitattributes

          # Ensure the 3 runtime files are present (edit if you keep them elsewhere)
          test -f requirements.txt || (echo "ERROR: requirements.txt missing" && exit 1)
          test -f README.md        || (echo "ERROR: README.md missing" && exit 1)

          # Commit everything in the snapshot
          git add -A
          git commit -m "Deploy snapshot for HF Space (LFS pointers, heavy tests removed)"

      - name: Push to Space (main)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        working-directory: deploy
        run: |
          # Add Space remote with token (no secrets committed)
          git remote add space https://JackyyyWang:${HF_TOKEN}@huggingface.co/spaces/JackyyyWang/BosonAI_Hackathon.git

          # Force-push this single-commit snapshot as Space's main
          git push --force space HEAD:main

          # Upload LFS objects referenced by this snapshot
          git lfs push --all space main
