name: Sync to Hugging Face hub

on:
  push:
    branches: [ hf-deploy ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source (with LFS metadata)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare deploy snapshot (exclude heavy test media)
        run: |
          rm -rf deploy && mkdir deploy
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.gitmodules' \
            --exclude='docs/' \
            --exclude='examples/' \
            --exclude='submodules/TTS/tests/' \
            --exclude='submodules/whisper/tests/' \
            --exclude='submodules/whisperX/figures/' \
            --exclude='submodules/demucs/test.mp3' \
            ./ deploy/

      - name: Initialize clean repo & track binaries with LFS
        working-directory: deploy
        run: |
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git lfs install
          printf "%s\n" \
            "*.png filter=lfs diff=lfs merge=lfs -text" \
            "*.jpg filter=lfs diff=lfs merge=lfs -text" \
            "*.jpeg filter=lfs diff=lfs merge=lfs -text" \
            "*.gif filter=lfs diff=lfs merge=lfs -text" \
            "*.mp3 filter=lfs diff=lfs merge=lfs -text" \
            "*.wav filter=lfs diff=lfs merge=lfs -text" \
            "*.flac filter=lfs diff=lfs merge=lfs -text" \
            "*.npy filter=lfs diff=lfs merge=lfs -text" \
            "*.pt filter=lfs diff=lfs merge=lfs -text" \
            "*.pth filter=lfs diff=lfs merge=lfs -text" \
            "*.ttf filter=lfs diff=lfs merge=lfs -text" \
            > .gitattributes
          test -f README.md || (echo "ERROR: README.md missing" && exit 1)
          test -f requirements.txt || (echo "ERROR: requirements.txt missing" && exit 1)
          git add -A
          git commit -m "Deploy snapshot for HF Space (LFS pointers, heavy tests removed)"

      - name: Push snapshot to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        working-directory: deploy
        run: |
          git remote add space "https://JackyyyWang:${HF_TOKEN}@huggingface.co/spaces/JackyyyWang/BosonAI_Hackathon.git"
          git push --force space HEAD:main
          git lfs push --all space main
