name: Sync to Hugging Face hub
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Install Git LFS
        run: |
          git lfs install
          git lfs fetch --all
          git lfs status
      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://huggingface.co/spaces/JackyyyWang/BosonAI_Hackathon
          # force push current HEAD to main on the Space
          git push --force https://JackyyyWang:${HF_TOKEN}@huggingface.co/spaces/JackyyyWang/BosonAI_Hackathon HEAD:main
